### ISSUE TITLE
Errore di valore assoluto

### ISSUE THREAD

**Issue by davella97** [msc-technology/avogadro-challenge-2024#1]
Buonasera, sono uno studente dell'itis avogadro.
Mentre cercavo di risolvere la challenge ho riscontrato un errore quando il programma cerca di comparare i risultati del sorting intelligente e del sorting "dumb". Premetto che non sono sicuro di aver ancora trovato una soluzione giusta :  quando si avvia il programma e si arriva al momento della comparazione (se non si verificano altri errori prima), il programma cerca di fare valore assoluto del risultato intelligente (smartCenterOfMassRelativeToIdealPosition.x) minore di "dumbCenterOfMassRelativeToIdealPosition.X", ma ci sono volte in cui "dumbCenterOfMassRelativeToIdealPosition.X" risultata in un numero inferiore a zero, per cui la comparazione con un valore assoluto è insensata dato che in risultato sarà sempre false. Sto sbagliando io qualcosa?
![image](https://github.com/msc-technology/avogadro-challenge-2024/assets/105510059/405042e6-31be-411d-9f2c-d76f5b4b397a)

**Comment by sabbadino** [comment]
Ciao, appena riesco verifico la tua segnalazione

**Comment by sabbadino** [comment]
Ciao, certo .. è un errore .. il valore assoluto deve essere da entrambe le parti del confronto

**Comment by davella97** [comment]
> Ciao, certo .. è un errore .. il valore assoluto deve essere da entrambe le parti del confronto

ah ok, grazie per la risposta, buona giornata
